<script setup>
import { ref } from "vue";
import { useAuthStore } from "@/stores/auth";
import { useRouter } from "vue-router";
import BaseAlertError from "@/components/Alert/BaseAlertError.vue";
import BasePasswordInput from "@/components/input/BasePasswordInput.vue";
import BaseLoading from "@/components/BaseLoading.vue";
import { watch } from "vue";
import BaseAlertSuccess from "@/components/Alert/BaseAlertSuccess.vue";

const authStore = useAuthStore();
const { recoverPassword } = authStore;

const loading = ref(false);
const error = ref(false);
const router = useRouter();
const disabled = ref(true);
const success = ref(false);
const payload = ref({
  email: "",
  nova_senha: "",
});

const handleSubmit = async () => {
  loading.value = true;

  if (payload.value.email && payload.value.nova_senha) {
    const newPassword = await recoverPassword(payload.value);
    if (newPassword) {
      success.value = true;

      setTimeout(() => {
        success.value = false;
      }, 3000);

      //router.push({ name: "login" });
    }
  } else {
    error.value = true;

    setTimeout(() => {
      error.value = false;
    }, 3000);
  }
  loading.value = false;
};

const handleKeyPress = (event) => {
  if (event.key === "Enter" && !disabled.value) {
    handleSubmit();
  }
};

watch(payload.value, () => {
  if (payload.value.email.length > 1 && payload.value.nova_senha.length > 1) {
    disabled.value = false;
  } else {
    disabled.value = true;
  }
});
</script>

<template>
  <div class="flex login-view-container">
    <div class="form-container">
      <div class="form flex column">
        <h2 class="poppins-medium">Recuperar Senha</h2>

        <div class="flex column input-container">
          <label>Email</label>
          <input
            type="email"
            placeholder="Insira seu email"
            :value="payload.email"
            @input="(ev) => (payload.email = ev.target.value)"
            @keydown="handleKeyPress"
          />
        </div>
        <div class="flex column input-container">
          <label>Nova senha</label>

          <input
            type="password"
            placeholder="Insira sua nova senha"
            :value="payload.nova_senha"
            @input="(ev) => (payload.nova_senha = ev.target.value)"
            @keydown="handleKeyPress"
          />
        </div>

        <button
          class="button"
          @click="handleSubmit"
          :class="disabled === true ? 'disabled' : ''"
          :disabled="disabled"
        >
          <span v-if="!loading">Recuperar Senha</span>
          <div
            v-else
            style="
              width: 100%;
              display: flex;
              align-items: center;
              justify-content: center;
            "
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 100 100"
              preserveAspectRatio="xMidYMid"
              width="28"
              height="28"
              style="
                shape-rendering: auto;
                display: block;
                background: rgba(255, 255, 255, 0);
              "
              xmlns:xlink="http://www.w3.org/1999/xlink"
            >
              <g>
                <circle
                  stroke-dasharray="164.93361431346415 56.97787143782138"
                  r="35"
                  stroke-width="10"
                  stroke="#fff"
                  fill="none"
                  cy="50"
                  cx="50"
                >
                  <animateTransform
                    keyTimes="0;1"
                    values="0 50 50;360 50 50"
                    dur="1s"
                    repeatCount="indefinite"
                    type="rotate"
                    attributeName="transform"
                  ></animateTransform>
                </circle>
                <g></g>
              </g>
              <!-- [ldio] generated by https://loading.io -->
            </svg>
          </div>
        </button>

        <img
          class="logo"
          src="../../assets/img/png/logo-1.png"
          alt=""
          style="width: 110px; margin: auto"
        />
        <BaseAlertSuccess
          v-if="success"
          type="success"
          text="Senha recuperada com sucesso!"
        />
        <BaseAlertError
          v-if="error"
          type="error"
          text="Preencha todos os campos"
        />
      </div>
    </div>
    <div class="theme">
      <img src="../../assets/img/png/universitaria-estudando.jpg" alt="theme" />
    </div>
  </div>
</template>

<style scoped lang="scss">
.disabled {
  opacity: 0.7;
}

h2 {
  text-align: center;
}

.password-span-text {
  color: var(--secondary);
  text-align: end;
  text-decoration: none;
  margin-left: 2px;
}
.login-span-text {
  color: var(--secondary);
  text-align: left;
  text-decoration: none;
}
.login-view-container {
  max-height: 100vh;
  overflow: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
}

.theme {
  width: 50%;
  background-color: black;
  img {
    width: 100%;
    opacity: 0.6;
    height: 100vh;
    object-fit: cover;
    position: relative;
  }
}
.form-container {
  width: 50%;
  padding: 2rem;

  .form {
    gap: 0.8rem;
    width: 450px;
    margin: auto;
    position: relative;

    h1 {
      text-align: center;
      font-size: 55px;
    }
    .input-container {
      gap: 0.3rem;
      input {
        padding: 0.7rem;
        border-radius: 8px;
        border: 1px solid #24242475;

        width: 100%;
      }
    }

    .button {
      background-color: var(--secondary);
      color: #fff;
      padding: 0.7rem;
      border: 1px solid rgba(83, 83, 83, 0.219);
      border-radius: 8px;
      font-size: 1rem;
      cursor: pointer;
    }

    @media (max-width: 1110px) {
      width: 90%;
    }
  }
}
@media (min-width: 0px) and (max-width: 850px) {
  .theme {
    display: none;
  }

  .form-container {
    width: 100%;
    height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
  }
}
</style>
